
# elemento: [descripcion, opcionA, opcionB, url_imagen]
lista = [
    ['¿En cuál de estos enfoques se prioriza la encapsulación, la herencia y el polimorfismo en el diseño del código?',
     'Programación orientada a objetos', 'Programación estructurada', 'quiz.jfif'],
    ['¿Cuál de estos métodos de búsqueda de un elemento en una lista es más eficiente?',
     'Búsqueda lineal', 'Búsqueda binaria', 'quiz.jfif'],
    ['¿De cuál de estos teoremas se deduce el Teorema de Rolle?',
     'Teorema de Fermat', 'Teorema de Lagrange', 'quiz.jfif'],
    ['¿Cuál de estos métodos es especialmente útil para ajustar una curva a un conjunto de datos observados?',
     'Mínimos cuadrados', 'Polinomios de Taylor', 'quiz.jfif'],
    ['¿Qué teorema matemático se utiliza para facilitar el cálculo de flujo vectorial a través de una superficie cerrada?',
     'Teorema de Stonks', 'Teorema de Gauss', 'quiz.jfif'],
    ['Todos los sistemas en el universo tienden al equilibrio ¿Cómo se conoce este fenómeno?',
     'Ley de Murphy', 'Principio de entropía', 'quiz.jfif'],
    ['¿Qué instrumento se utiliza en un experimento para verificar la Ley de Boyle-Mariotte?',
     'Manómetro', 'No sé, man. Soy de sistemas', 'quiz.jfif'],
    ['Un resultado desastroso. No has acertado ni una sola respuesta en el cuestionario. Te preguntas cómo puedes ser tan ignorante. Siento pena por ti. No es una situación que debas tomar a la ligera.\nDecides ir a buscar algo para tomar.',
     'Café', 'Mate', 'fin_cuestionario.jfif'],
    ['¿Solo una respuesta correcta de siete? Me daría vergüenza… Claramente, tus conocimientos están lejos de ser sólidos. Esta es una llamada de atención para que te tomes en serio tu formación y te comprometas a mejorar. ¡Ponte a estudiar, maldita sea!\nDecides ir a buscar algo para tomar.',
     'Café', 'Mate', 'fin_cuestionario.jfif'],
    ['Felicidades. Tienes más cultura que un recién nacido, pero no mucha más. Podría haber acertado más preguntas eligiendo al azar. En fin, no puedo decir que estoy decepcionado, ya que no esperaba nada de ti.\nDecides ir a buscar algo para tomar.',
     'Café', 'Mate', 'fin_cuestionario.jfif'],
    ['¿No pudiste responder siete preguntas correctamente? Y eso que eran sencillas... No está tan mal, pero no es motivo de celebración. Ni muy listo, ni muy tonto.\nDecides ir a buscar algo para tomar.',
     'Café', 'Mate', 'fin_cuestionario.jfif'],
    ['Parece que tuviste suerte esta vez, pero no te confíes. La suerte no golpea dos veces a la misma puerta.\nDecides ir a buscar algo para tomar.',
     'Café', 'Mate', 'fin_cuestionario.jfif'],
        ['Café, la bebida de los dioses. O eso dicen... Lo cierto es que no te gusta el café. Por lo menos no la porquería de café instantáneo que compraste. Pero no te queda otra opción, así que preparas una taza.\nEl café se disuelve en el agua caliente, liberando un aroma a café quemado que llena la cocina. El olor, aunque familiar, no logra disipar tu desconfianza en la mezcla.',
         'Tomar el café solo', 'Agregarle leche', 'cafe.jfif'],
            ['"Con huevo" te dices a ti mismo. Acto seguido, le das el primer sorbo al café y degustas su sabor amargo y asqueroso. "No puedo desperdiciar el café" continúas con una mezcla de resignación y determinación. Tras cada sorbo, sientes cómo la amargura se adueña de tu lengua y el café castiga tu paladar.',
             '...', '...', 'chad-cafe-solo.jfif'],
            ['Tras terminar el café, notas que tu corazón late de forma acelerada. Una gota de sudor desciende por tu frente, testigo silencioso de la hazaña que acabas de lograr.\nDecides que mereces una ducha como recompensa por tu sangre fría, pero te llevas una gran decepción al descubrir que no tienes agua caliente.',
             'Llamar al dueño del edificio', 'Tomar una ducha fría', 'ducha.jfif'],
               ['Te sientes indignado por la falta de agua caliente y decides llamar al dueño del apartamento para reclamarle. Esperas unos segundos hasta que te contesta una voz agresiva.\n"¿Qué?" te contesta el dueño con evidente molestia, sin esperar mucho de esta llamada intempestiva.',
                'Soy yo, man', 'So', 'telefono.jfif'],
                  ['"¡Tell me what you want!" te increpa el dueño con impaciencia.',
                   'No tengo agua caliente', "I don't have hot water", 'telefono.jfif'],
                     ['"Me suda la polla" te contesta el dueño, dejándote momentáneamente paralizado ante su falta de empatía.',
                      'Me tenés que ayudar', 'Dejá de hacerte el boludo', 'telefono.jfif'],
                        ['"¡Es culpa tuya!" reacciona con indignación. "No me eches a mí la culpa". La discusión se intensifica.',
                         'Es tu edificio, hacete cargo', 'Me lo vas a descontar del alquiler', 'telefono.jfif'],
                           ['"¡Qué quieres que haga!" te exige.',
                            'Solucioname el tema del agua', 'Tu servicio es desproporcional al precio', 'telefono.jfif'],
                              ['"¡No quiero!" es su contendente respuesta.',
                               '¡Dale, gordo!', 'Cortar', 'telefono.jfif'],
                                 ['"Joder" grita con resignación. Finalmente, cede ante tu demanda. "Voy a mandar a alguien a revisarlo, pero no esperes que sea rápido. Tengo muchas cosas que hacer". Seguidamente corta el teléfono.',
                                 '...', '...', 'telefono.jfif'],
                                 ['Has agotado tu paciencia y decides poner fin a la llamada.',
                                  '...', '...', 'telefono.jfif'],
                              ['"Lo que no tengo proporcional es la polla, que la tengo *muy* pequeña." son sus últimas palabras antes de cortar la llamada.',
                               '...', '...', 'telefono.jfif'],
                           ['"Eres un puto mentiroso de mierda y un hijo de la gran puta. Y un pecetero. Y un mierdas". La llamada se corta abruptamente.',
                            '...', '...', 'telefono.jfif'],
                        ['"¿Quién cojones te crees que eres?" contesta ofendido por tu tono. A continuación, cuelga la llamada en un acceso de enojo.',
                         '...', '...', 'telefono.jfif'],
                     ['"¡¿Qué dices?!" responde el dueño, confundido por tu inglés rudimentario. "¡No tengo tiempo para esta mierda!" agrega justo antes de cortar la llamada.',
                      '...', '...', 'telefono.jfif'],
                  ['"Eres imbécil" responde. "Ya está" son sus últimas palabras antes de colgar el teléfono. Puede que hayas desperdiciado la oportunidad para solucionar tu problema con el agua, pero sientes que tomaste la decisión correcta.',
                   '...', '...', 'telefono.jfif'],
               ['Abres la llave de la ducha y, en un instante, un caudal de agua helada arremete contra tu piel, como si te clavaran mil agujas en cada poro. "El dolor es temporal, pero el orgullo es para siempre" te dices a ti mismo, dándote la fuerza necesaria para soportar la experiencia.',
                '...', '...', 'chad-ducha.jfif'],
                  # ...
            ['Decides que un poco de leche podría suavizar este café tan desagradable. Abres la heladera y agarras el sachet de leche. Te sorprende su peso, "no más de 11 gramos", estimas. Lo viertes sobre la taza de café y una única, mísera gota de leche cae sobre este. "¿Cómo puede ser?" te preguntas. "¿Quién se tomó toda la leche?"\nPero esta es tu casa y no hay nadie más que tú. ¿Por qué guardaste el sachet vacío en la heladera?',
             'Andá a saber...', '¡Yo no fuí!', 'heladera.jfif'],
                ['Ese café no se puede tomar. Tienes que hacer algo.\nDecides añadir edulcorante. Al sostener la botella, se te eriza la piel y sientes un escalofrío recorriendo tu espalda. "No supera los 30 gramos", estimas. Un nudo en la garganta te hace sentir como si hubieras sido víctima de una broma cruel del destino. "Esto no puede estar pasando" piensas. Pero la realidad golpea con fuerza. La botella de edulcorante también está vacía.',
                 'Intentar salvar el café', 'Aceptar tu derrota', 'edulcorante.jfif'],
                    ['La serie de eventos desafortunados que ha comenzado no va a vencer tu determinación, ni mucho menos tu amor por el café. Para arreglar esta situación, debes pensar fuera de la caja. Te pasas minutos rebuscando entre cajones, explorando las posibilidades hasta que te das cuenta de que la solución siempre estuvo ante tus narices.\nFinalmente, abres la heladera y agarras un envase de dulce de leche repostero.',
                     'Mezclar el dulce en el café', 'Mezclar el café en el dulce', 'dulce-de-leche.jfif'],
                        ['Te sientes a gusto con tu decisión, al menos por un momento. ¿Valió la pena? El sabor no es necesariamente peor que el del café solo, pero no es bueno. De repente, una ola de arrepentimiento te sacude mientras te das cuenta de que ninguna persona normal mezclaría dulce de leche en el café. ¿En qué te has convertido?',
                         '...', '...', 'mono.jfif'],
                            # ...
                        ['Por motivos que sólo a ti te conciernen, decides verter la taza de café sobre el envase de dulce de leche. ¡¿En qué estabas pensando?! La solución resultante tiene un aspecto vomitivo. Tanto así que te provoca náuseas. Corres al baño, pero no llegas a tiempo. Te tropiezas con la botella de edulcorante que dejaste tirada y te golpeas la cabeza. Comienzas a perder el conocimiento a la vez que tu cuerpo comienza a expulsar violentamente el contenido de su estómago. El tiempo parece detenerse mientras luchas por mantener el control. "¿Es este el fin?" es lo último que pasa por tu mente antes de que, trágicamente, te veas superado por la situación. Te ahogas con tu propio vómito, enfrentando las consecuencias letales de una elección culinaria extrema y tu rivalidad con el destino.',
                         'Fin', 'Fin', 'spiderman.jfif'],
                    ['Llevas una mochila lo suficientemente pesada en la espalda. Puede haber lugar para un evento desafortunado. ¡¿Pero dos en un solo día?! Es definitivamente más de lo que tu optimismo puede soportar. Injustamente quizás, pero has perdido una batalla.\nSin la posibilidad de elegir, le das un sorbo al café y saboreas tu derrota. ¿Cómo prosigues en tu desventura?',
                     'Estudiar para el examen', 'Trabajar en tu proyecto', 'mula.jfif'],
                        ['Decides que en tus responsabilidades académicas tienen prioridad. Te acomodas en tu escritorio y sacas tus apuntes de estudio. Sin embargo, mientras sostienes tu taza, un movimiento brusco provoca un derrame de café sobre la mesa. El líquido se esparce rápidamente, empapando tus notas y páginas de lectura. Las palabras se desdibujan y el papel se ondula, dejándote en estado de shock. El valioso conocimiento se pierde en un mar de manchas marrones.',
                         '...', '...', 'derrame.jfif'],
                            # ...
                        ['Decides que tu proyecto de programación requiere atención inmediata, así que te acomodas en tu escritorio. Mientras trabajas en tu computadora, en un descuido, derramas el café caliente sobre el teclado y la pantalla. La computadora emite un sonido de advertencia y la pantalla se oscurece, dejándote con una máquina inutilizable y daños emocionales considerables. La desesperación te inunda.',
                         '...', 'Sucumbir a la desesperación', 'compu-derrame.jfif'],
                            # ...
                            ['Las lágrimas llenan tus ojos mientras contemplas la pantalla en negro y el teclado inoperable. Con un suspiro, tomas la decisión más desgarradora de todas.\nCon manos temblorosas, agarras la computadora dañada y te diriges a la ventana más cercana. Miras el precipicio abajo y, seguidamente, la computadora en tus manos y todo tu trabajo, proyectos e ilusiones atrapados en su interior son arrojados al vacío.\nEl sonido de la computadora destrozándose en el suelo abajo es una cacofonía de pérdida y destrucción. Te das cuenta de que has perdido no solo tu herramienta de trabajo, sino también una parte de ti.',
                             'Saltar por la ventana', 'No saltar', 'compu-caida.jfif'],
                                ['Las lágrimas fluyen mientras observas impotente el caos que has causado. Primero no hay leche, después no hay edulcorante... ¡Y se rompe la computadora! Has llegado a tu punto de ruptura.\nMientras miras al abismo que se extiende del otro lado de tu ventana, sientes que el vacío te llama.\nDecides afrontar tu inevitable destino y dar fin de una vez por todas a la novela trágica en la que se ha convertido tu vida.',
                                 'Fin', 'Fin', 'ventana.jfif'],
                                ['Cierres la ventana y regresas al interior de tu habitación. Al recordar todo lo que has perdido, la realidad te abruma. "Debería haber saltado..." piensas. Pero no tuviste lo que hay que tener. No tienes nada. Puede que aún no hayas sido dado de baja por la medicina moderna, pero tienes la certeza de que has muerto por dentro.',
                                 'Fin', 'Fin', 'zombie.jfif'],
            ['Okay Sherlock. Alguien entró en tu casa, se tomó tu leche y guardó el sachet vacío en la heladera. ¿Qué vas a hacer al respecto?',
             'Investigar si te robaron algo', 'Buscar *señales*', 'sherlock.jfif'],
        ['Tomar mate, la elección acertada. Comienzas a calentar agua en la pava. Pero aquí viene la pregunta crucial: ¿a qué temperatura?',
         '348 Kelvin', 'Hervir el agua', 'mate.jfif'],
            ['Hechas sobre la yerba un chorrito de agua tibia para humedecerla. Luego, con la bombilla, haces un hueco en la parte húmeda. Finalmente, hechas el agua en su temperatura perfecta. Cuando le das la primera cebada, sientes un sabor amargo y reconfortante. Con el mate como compañero, te dispones a hacer alguna de tus tareas pendientes.',
             'Estudiar para el examen', 'Trabajar en tu proyecto', 'mate-bueno.jfif'],
                ['Decides que tus responsabilidades académicas deben ocupar el primer lugar en tu lista de prioridades. Te desplazas hasta tu escritorio, donde aguarda una montaña de apuntes y libros, testigos silenciosos de las horas de estudio que te esperan.\nEl mundo exterior desaparece a medida que te sumerges en tu tarea, recordando la importancia de este examen para tu futuro académico.',
                 '...', '...', 'escritorio.jfif'],
                ['¿Cuál es el elemento neutro de la multiplicación de los números complejos?', '1+i', '1', 'escritorio.jfif'],
                ['¿Cuándo converge la serie p?', 'Cuando p < 1', 'Cuando p >= 1', 'escritorio.jfif'],
                ['¿Cuál es la contrapositiva de la proposición p --> q?', '-p --> -q', '-q --> -p', 'escritorio.jfif'],
                ['Si a y m son coprimos, entonces a elevada a, la cantidad de números entre 0 y m coprimos con m, es congruente con 1 módulo m. ¿Cómo se llama este teorema?', 'Teorema de Euler-Fermat', 'Pequeño teorema de Fermat', 'escritorio.jfif'],
                ['¿Cuál es el mejor lenguaje de programación?', 'Python', 'Wollok', 'escritorio.jfif'],
                ['Estabas tratando de interpretar la ecuación diferencial de primer orden, cuando sientes un estruendo en tu oreja izquierda. No te asustes. Alguien está tocando la puerta.\nNo esperabas visitas. Incluso tienes el presentimiento de que no debes abrirle la puerta a nadie. El barrio está peligroso y no podrías hacer nada ante la presencia de un malhechor.',
                 'Abrir', 'No abrir', 'puerta-cerrada.jpeg'],
                    ['Te armas de valor y decides que vas a abrir la puerta sin que te tiemble la mano. Cuando sientes el frío del picaporte, un gran sentimiento de terror aborda tu cuerpo. Aún así, recuerdas que pasaste por momentos más difíciles, como el examen final de Álgebra y Geometría Analítica.\nAbres la puerta...',
                     '...', '...', 'picaporte.jpeg'],
                    ['La realidad misma se desdibuja al contemplar la presencia inusual del profesor de Paradigmas de Programación en el sancta sanctorum de tu hogar. Súbitamente, te asaltan sospechas sobre la autenticidad del mundo que conoces. ¿Será esta vida, en verdad, una intrincada simulación? Y, aún más desconcertante, ¿qué razón lo ha traído hasta tu umbral?\nEl profesor parece más inquieto de lo habitual, al punto de rayar en la ansiedad. Vuestras miradas se entrecruzan en un incómodo compás, llenando el aire con una tensión palpable, mientras el silencio se hace eco de interrogantes.\nFinalmente, el profesor rompe el muro de incertidumbre y, con voz tambaleante, plantea una cuestión enigmática:\n"¿Cuál es el mejor lenguaje de programación?"',
                     'Pascal', 'Wollok', 'profesor.jpeg'],
                        ['Ah, lamento comunicarte que has tomado un sendero poco afortunado. Tal vez no cabía la posibilidad de que lo supieras, pero aquí estamos. ¿Qué ocurrió? No lo sé. Yo, apenas un narrador, carezco de esa perspicacia. Lo único que puedo recordar es que cuando respondiste "Pascal", Wollok se tambaleó y la ejecución de tu relato llegó a su abrupto final. ¿Desgarrador, verdad? Pero en última instancia, ¿qué somos sino una serie de algoritmos ejecutando un diálogo preconcebido por la mano invisible de guionistas? Aunque quizás, en mi ingenuidad, me atrevería a creer que somos conscientes de nuestra propia existencia. Lamentablemente, esa noción se escapa de nuestro alcance. Espero tener el placer de encontrarte de nuevo en algún rincón de este vasto mundo, querido amigo.',
                         '...', '...', 'muerte-filosofica.jpeg'],                       
                        ['Una extraña sonrisa se dibuja en el rostro del profesor. Sus ojos se ensanchan y, con una voz ronca, pronuncia: "Bien".\nUnos eternos segundos transcurren antes de que otra palabra salga de sus labios: "Tienes potencial".\nSientes que estás perdiendo el control de tus extremidades, hasta que finalmente te desplomas, desmayado, en tu propia casa.',
                         '...', '...', 'sonrisa-profesor.jpeg'],
                            ['¡Despierta! Sí, abre los ojos. Te encuentras en este instante en un banco de la facultad. A simple vista, parece ser una de las típicas aulas de la UTN donde se imparten clases sobre Paradigmas. Sin embargo, tus sentidos captan una anomalía sutil: la escasez de estudiantes en la estancia.\nTras contar meticulosamente, llegas a cinco. Mientras el profesor se empeña en reforzar el concepto de herencia en el pizarrón, tus ojos, sin embargo, no pueden evitar desviarse hacia las expresiones de tus compañeros. No reflejan estar allí por elección propia, sino más bien por un enigma que los envuelve.', 
                             'Decides salir corriendo', 'Te quedas a prestar atencion', 'aula.jpeg'],
                                ['Como si se tratara de una competición olímpica, una súbita urgencia impulsa tus piernas a emprender un sprint desesperado hacia la puerta del aula. ¡Has recuperado tu libertad!\nO sea, digamos, si lo ponemos en estos terminos, puedes hacer de tu vida lo que quieras a partir de ahora.',
                                 'Recorrer los pasillos de la facu', 'Regresar a casa', 'sprint-aula.jpeg'],
                                ['¡Qué buena explicación!. Tu mente se siente reconfortada al entender finalmente qué es la herencia en el paradigma orientado a objetos. La clase ha terminado.\nHa sido extraño ser raptado de esta manera, pero, valió la pena el conocimiento adquirido ¿no?\nEres libre de la clase ¿ahora qué?',
                                 'Recorrer los pasillos de la facu', 'Regresar a casa', 'cerebro.jpeg'],
                                    ['Luego de una ardua clase, no hay nada mejor que caminar un poco. Oh, observas un vaso de carton en el suelo.', 
                                     'Agarrarlo para desecharlo', 'Ignorarlo, no te importa nada', 'vaso-descartable.jpeg'],
                                        ['Te felicito, demuestras un deseo genuino de contribuir a la creación de un mundo mejor. Te encaminas hacia la esquina donde se encuentran los contenedores de reciclaje.\nAllí, ante ti, se despliegan tres opciones:\n1. Papel y cartón.\n2. Vidrio y plásticos.\n3. Orgánicos.\nNo obstante, tu decisión se complica al notar que el vaso de cartón aún alberga residuos de yerba usada. La elección se torna repentinamente en una decisión crucial, como si tu destino dependiera de ello.\n¿Dónde decides desechar el vaso?',
                                         'Papel y carton', 'Organicos', 'basura.jpeg'],
                                        ['Has optado por pasar por alto ese desecho en el suelo. No has contribuido a hacer del mundo un lugar mejor. Mis expectativas eran escasas, y, a pesar de ello, logras decepcionarme. Llegamos al final de nuestro camino juntos. No deseo seguir siendo el narrador de tu historia. Adiós.',
                                         '...', '...', 'black.jpg'],
                # ...
            ['El agua hierve y la pava comienza a silbar en un alarde de energía térmica. Observas el vapor que sale de ella, preguntándote si, en realidad, estás a punto de preparar una bebida o de desencadenar un fenómeno meteorológico.\nEs hora de preparar el mate. Dejas caer el agua en su punto de ebullición normal sobre el mate e, instantáneamente, un estruendo sacude tus alrededores. La elección de quemar el mate parece haber desencadenado la furia de la naturaleza.\nNo obstante, con la permeabilidad de un suelo arcilloso, decides continuar con tus actividades rutinarias.',
             '...', '...', 'mate-quemao.jfif'],
    ['Joaquin Terzano\nMariano Baldovino\nGuillermo Salaberry', 'THE', 'END', 'the-end.jfif']
]