
# elemento: [descripcion, opcionA, opcionB, url_imagen]
lista = [
      ['¿En cuál de estos enfoques se prioriza la encapsulación, la herencia y el polimorfismo en el diseño del código?',
       'Programación orientada a objetos', 'Programación estructurada', 'quiz.jfif', 'quiz-0'],
      ['¿Cuál de estos métodos de búsqueda de un elemento en una lista es más eficiente?',
       'Búsqueda lineal', 'Búsqueda binaria', 'quiz.jfif', 'quiz-1'],
      ['¿De cuál de estos teoremas se deduce el Teorema de Rolle?',
       'Teorema de Fermat', 'Teorema de Lagrange', 'quiz.jfif', 'quiz-2'],
      ['¿Cuál de estos métodos es especialmente útil para ajustar una curva a un conjunto de datos observados?',
      'Mínimos cuadrados', 'Polinomios de Taylor', 'quiz.jfif', 'quiz-3'],
      ['¿Qué teorema matemático se utiliza para facilitar el cálculo de flujo vectorial a través de una superficie cerrada?',
      'Teorema de Stonks', 'Teorema de Gauss', 'quiz.jfif', 'quiz-4'],
      ['Dados dos vértices u y v de un árbol enraizado. ¿Qué proposición es equivalente a afirmar que existe un camino que empieza en v y acaba en u?',
      'v es padre de u', 'u es descendiente de v', 'quiz.jfif', 'quiz-5'],
      ['¿Qué instrumento se utiliza en un experimento para verificar la Ley de Boyle-Mariotte?',
      'Manómetro', 'No sé, man. Soy de sistemas', 'quiz.jfif', 'quiz-6'],
      ['Un resultado desastroso. No has acertado ni una sola respuesta en el cuestionario. Te preguntas cómo puedes ser tan ignorante. Siento pena por ti. No es una situación que debas tomar a la ligera.\nDecides ir a buscar algo para tomar.',
      'Café', 'Mate', 'fin_cuestionario.jfif', 'resultado-0'],
      ['¿Solo una respuesta correcta de siete? Me daría vergüenza… Claramente, tus conocimientos están lejos de ser sólidos. Esta es una llamada de atención para que te tomes en serio tu formación y te comprometas a mejorar. ¡Ponte a estudiar, maldita sea!\nDecides ir a buscar algo para tomar.',
      'Café', 'Mate', 'fin_cuestionario.jfif', 'resultado-1'],
      ['Felicidades. Tienes más cultura que un recién nacido, pero no mucha más. Podría haber acertado más preguntas eligiendo al azar. En fin, no puedo decir que estoy decepcionado, ya que no esperaba nada de ti.\nDecides ir a buscar algo para tomar.',
      'Café', 'Mate', 'fin_cuestionario.jfif', 'resultado-2'],
      ['¿No pudiste responder siete preguntas correctamente? Y eso que eran sencillas... No está tan mal, pero no es motivo de celebración. Ni muy listo, ni muy tonto.\nDecides ir a buscar algo para tomar.',
      'Café', 'Mate', 'fin_cuestionario.jfif', 'resultado-3'],
      ['Parece que tuviste suerte esta vez, pero no te confíes. La suerte no golpea dos veces a la misma puerta.\nDecides ir a buscar algo para tomar.',
      'Café', 'Mate', 'fin_cuestionario.jfif', 'resultado-4'],
         ['Café, la bebida de los dioses. O eso dicen... Lo cierto es que no te gusta el café. Por lo menos no la porquería de café instantáneo que compraste. Pero no te queda otra opción, así que preparas una taza.\nEl café se disuelve en el agua caliente, liberando un aroma a café quemado que llena la cocina. El olor, aunque familiar, no logra disipar tu desconfianza en la mezcla.',
            'Tomar el café solo', 'Agregarle leche', 'cafe.jfif', 'cafe'],
            ['"Con huevo" te dices a ti mismo. Acto seguido, le das el primer sorbo al café y degustas su sabor amargo y asqueroso. "No puedo desperdiciar el café" continúas con una mezcla de resignación y determinación. Tras cada sorbo, sientes cómo la amargura se adueña de tu lengua y el café castiga tu paladar.',
             '...', '...', 'chad-cafe-solo.jfif', 'chad-cafe-solo'],
            ['Tras terminar el café, notas que tu corazón late de forma acelerada. Una gota de sudor desciende por tu frente, testigo silencioso de la hazaña que acabas de lograr.\nDecides que mereces una ducha como recompensa por tu sangre fría, pero te llevas una gran decepción al descubrir que no tienes agua caliente.',
             'Llamar al dueño del edificio', 'Tomar una ducha fría', 'ducha.jfif', 'ducha-0'],
               ['Te sientes indignado por la falta de agua caliente y decides llamar al dueño del apartamento para reclamarle. Esperas unos segundos hasta que te contesta una voz agresiva.\n"¿Qué?" te contesta el dueño con evidente molestia, sin esperar mucho de esta llamada intempestiva.',
                'Soy yo, man', 'So', 'telefono.jfif', 'telefono-0'],
                  ['"¡Tell me what you want!" te increpa el dueño con impaciencia.',
                   'No tengo agua caliente', "I don't have hot water", 'telefono.jfif', 'telefono-01'],
                     ['"Me suda la polla" te contesta el dueño, dejándote momentáneamente paralizado ante su falta de empatía.',
                      'Me tenés que ayudar', 'Dejá de hacerte el boludo', 'telefono.jfif', 'telefono-02'],
                        ['"¡Es culpa tuya!" reacciona con indignación. "No me eches a mí la culpa". Sientes como la temperatura de tu cuerpo se eleva a medida que la discusión se intensifica.',
                         'Es tu edificio, hacete cargo', 'Me lo vas a descontar del alquiler', 'telefono.jfif', 'telefono-03'],
                           ['"¡Qué quieres que haga!" te exige, mientras tu cuerpo continúa absorbiendo el calor de su ambiente.',
                            'Solucioname el tema del agua', 'Tu servicio es desproporcional al precio', 'telefono.jfif', 'telefono-04'],
                              ['"¡No quiero!" es su contendente respuesta. La temperatura del aire de la habitación cae por debajo de los 0 grados, mientras que el equilibrio térmico con tu cuerpo continúa alejándose.',
                               '¡Dale, gordo!', 'Cortar', 'telefono.jfif', 'telefono-05'],
                                ['"Joder" grita con resignación. Finalmente, cede ante tu demanda. "Voy a mandar a alguien a revisarlo, pero no esperes que sea rápido. Tengo muchas cosas que hacer". Seguidamente corta el teléfono.\nFelicidades, lo lograste. ¿Qué harás mientras esperas al sujeto?',
                                 'Estudiar para el examen', 'Trabajar en tu proyecto', 'telefono.jfif', 'telefono-06'],
                                  # Otro quiz
                                  ['El estado de trance en el que te hallabas se quiebra abruptamente al escuchar un llamado proveniente de la puerta principal. Supones que debe ser la persona que resolverá el problema del agua. Aunque la voz suena familiar, no logras identificar a quién pertenece.',
                                   'Abrir', 'Abrir, no me queda otra', 'puerta-cerrada.jpeg', 'llaman-puerta-0'],
                                  ['Cuando sientes el frío del picaporte, una oleada de terror recorre tu cuerpo. No hay motivos para desconfiar, pero un presentimiento desagradable se apodera de ti. Aún así, recuerdas que has pasado por momentos más difíciles, como el final de Análisis Matemático 1.\nCon cautela, abres la puerta...',
                                   '...', '...', 'picaporte.jpeg', 'llaman-puerta-1'],
                                  ['En el umbral de la puerta, una figura sombría te observa con una sonrisa siniestra. Conoces a esta persona, aunque preferirías no recordarla. Es el profesor de Paradigmas de la Programación, el mismo que te reprobó en dos ocasiones.\nUna sensación escalofriante se apodera de ti al verlo. ¿Qué demonios hace aquí el profesor? Tu mente trabaja a toda velocidad en busca de respuestas, pero antes de que puedas formular una pregunta, el profesor te lanza una mirada intensa y plantea una pregunta con tono ominoso: "¿Cuál es el mejor lenguaje de programación?" Su autoridad se impone sobre ti, y sientes la urgencia de responder',
                                    'Pascal', 'Wollok', 'profe-puerta.jfif', 'llaman-puerta-2'],
                                  # Trabajar en tu proyecto
                                ['Has agotado tu paciencia y decides poner fin a la llamada. Canalizas toda la energía térmica adquirida durante la discusión en un golpe contra el pobre aparato telefónico. La fuerza ejercida es tal que supera incluso las limitaciones establecidas por la segunda ley de la termodinámica, provocando una ruptura en la simulación. Este es el fin de tu historia.',
                                 'Fin', 'Fin', 'black.jpg', 'telefono-16'],
                              ['"Lo que no tengo proporcional es la polla, que la tengo *muy* pequeña." son sus últimas palabras antes de cortar la llamada.\nMientras terminas de procesar lo que acabas de escuchar, ¿por qué no aprovechas para ponerte al día con alguna de tus tareas pendientes?',
                               'Estudiar para el examen', 'Trabajar en tu proyecto', 'telefono.jfif', 'telefono-15'],
                                ['Decides que tus responsabilidades académicas deben ocupar el primer lugar en tu lista de prioridades. Te desplazas hasta tu escritorio, donde aguarda una montaña de apuntes y libros, testigos silenciosos de las horas de estudio que te esperan.\nEl mundo exterior desaparece a medida que te sumerges en tu tarea, recordando la importancia de este examen para tu futuro académico.',
                                 '...', '...', 'escritorio.jfif', 'intro-quiz2'],
                                ['¿Cuál es el elemento neutro de la multiplicación de los números complejos?',
                                 '1+i', '1', 'escritorio.jfif', 'quiz2-0'],
                                ['¿Cuándo converge la serie p?', 'Cuando p >= 1',
                                 'Cuando p < 1', 'escritorio.jfif', 'quiz2-1'],
                                ['¿Cuál es la contrapositiva de la proposición p --> q?',
                                 '-p --> -q', '-q --> -p', 'escritorio.jfif', 'quiz2-2'],
                                ['Si a y m son coprimos, entonces a elevada a, la cantidad de números entre 0 y m coprimos con m, es congruente con 1 módulo m. ¿Cómo se llama este teorema?',
                                 'Teorema de Euler-Fermat', 'Pequeño teorema de Fermat', 'escritorio.jfif', 'quiz2-3'],
                                ['¿Quieres que te haga caca en la cara?',
                                 'Si', 'No', 'escritorio.jfif', 'quiz2-caca'],
                                  ['El sonido agudo de un teléfono rompe el silencio de tu departamento. El timbre insiste en llamar tu atención, como si te recordara que el mundo exterior sigue existiendo. No hay razón para no contestar, ¿verdad?',
                                   'No, no la hay', 'Me da paja', 'telefono-1.jfif', 'suena-telefono-0'],
                                    ['Cuando finalmente te dignas a contestar el teléfono, no oyes nada. "¿Hola?" preguntas con cierta impaciencia. Del otro lado de la línea, una voz familiar te llega, con tono abatido. "Me he dejado las llaves dentro..." dice el dueño del edificio al borde del llanto, implorando clemencia.',
                                     'Jajajjajaaja', 'xDDDDD', 'telefono.jfif', 'contesta-telefono-0'],
                                    ['"¡No es gracioso!" interviene rápidamente. Como siempre, tienes dos opciones. ¿Lo ayudas o lo dejas a su suerte?',
                                     'Apiadarte del pobre infeliz', '¡Que se cague por gil!', 'telefono.jfif', 'contesta-telefono-1'],
                                       ['"Gracias por escuchar mis plegarias, tío." exclama con genuina gratitud. Das por hecho que el tema del agua estará solucionado al cabo de unos días.',
                                        '...', '...', 'telefono.jfif', 'contesta-telefono-apiadarse-0'],
                                          ['Habiendo realizado la buena acción del día, decides que es momento de ir a dormir.',
                                           '...', '...', 'cama.jfif', 'contesta-telefono-apiadarse-1'],
                                       ['"¡Me cago en tus muertos!" se oye desde la ventana. Por una vez, el karma parece funcionar y la realidad imparte justicia.',
                                        '...', '...', 'telefono.jfif', 'contesta-telefono-que-se-cague-0'],
                                          ['Con la satisfacción provocada por cómo se han desarrollado las cosas, decides que es hora de retirarte a descansar.',
                                          '...', '...', 'cama.jfif', 'contesta-telefono-que-se-cague-1'],
                                    ['"Eres un vago de mierda" oyes de repente. ¿Será tu cabeza haciéndote una mala pasada? Ojalá sea solo eso. Pero ahora debes contestar el teléfono para demostrar que no eres *un vago de mierda*.',
                                     'Contestar el *fucking* teléfono', 'Ser *un vago de mierda*', 'telefono-1.jfif', 'suena-telefono-1'],
                                       ['Te rindes ante las voces en tu cabeza. Dejas de lado tus estudios y, con el tiempo, pierdes tu trabajo debido a tu falta de compromiso.\nTe conviertes en un vagabundo, un alma perdida que deambula por las calles, sin sueños ni aspiraciones. No es un estilo de vida menos digno que cualquier otro.',
                                        'Fin', 'Fin', 'vagabundo.jfif', 'vagabundo-ending'],
                                ['Optas por continuar el desarrollo de tu videojuego en Wollok. Algo que en un principio parecía sencillo, pronto se convierte en una tarea desafiante. Cada línea de código parece estar rodeada de restricciones y obstáculos que dificultan la tarea. Wollok, aunque prometedora, se revela como un entorno de desarrollo complicado.',
                                 'Banco Wollok', 'Odio Wollok', 'compu.jfif', 'videojuego-0'],
                                ['Continúas programando el juego a pesar de las adversidades, hasta que oyes: "¿Cómo que un juego? ¿Eres imbécil tú, o qué te pasa? ¿Cómo que un juego?". La voz es enigmática, y no puedes determinar su origen, como si resonara en el rincón más oscuro de tu mente.',
                                 '¿Qué bardeas, pa?', '¿Qué decis?', 'compu.jfif', 'no-es-un-juego-0'],
                                ['La voz continúa: "Esto no es un juego. NADA es un juego". Este impactante recordatorio te hace detenerte en seco y reconsiderar tus elecciones.',
                                 'Esto ES un juego', 'NADA es un juego', 'compu.jfif', 'no-es-un-juego-1'],
                                  ['En efecto, esto es un juego. Una aventura interactiva, para ser precisos. Como la vida misma.\nQuizás te preguntes si hay algo que nos programa, nos limita o nos condiciona. Si somos realmente los jugadores de nuestra propia aventura, o si solo somos personajes jugables de una simulación ajena e inescapable. Quizás te preguntes si nuestras decisiones son realmente nuestras. Si tenemos alguna influencia sobre nuestra existencia, o si solo somos marionetas de una realidad que nos domina.\nDe aquí en adelante, estás por tu cuenta. Así que saca tus propias conclusiones.',
                                   'Fin', 'Fin', 'libertad.jfif', 'libertad-ending'],
                                  ['Esta nueva perspectiva te brinda argumentos para prescindir de terminar tu juego. Si nada es un juego, entonces eso es lo que vas a realizar.',
                                   'Brillante', 'Buee, la re pensaba...', 'cerebro.jpeg', 'no-es-un-juego-2'],
                                  ['Has hecho suficiente por hoy. Es hora de ir a dormir.',
                                   '...', '...', 'cama.jfif', 'ir-a-dormir'],
                           ['"Eres un puto mentiroso de mierda y un hijo de la gran puta, y un pecetero. Y un mierdas". La llamada se corta abruptamente.\nNo te lamentes todavía, tienes cosas que hacer.',
                            'Estudiar para el examen', 'Trabajar en tu proyecto', 'telefono.jfif', 'telefono-14'],
                        ['"¿Quién cojones te crees que eres?" contesta ofendido por tu tono. A continuación, cuelga la llamada en un acceso de enojo.\nNo te lamentes todavía, tienes cosas que hacer.',
                         'Estudiar para el examen', 'Trabajar en tu proyecto', 'telefono.jfif', 'telefono-13'],
                     ['"¡¿Qué dices?!" responde el dueño, confundido por tu inglés rudimentario. "¡No tengo tiempo para esta mierda!" agrega justo antes de cortar la llamada.\nNo te lamentes todavía, tienes cosas que hacer.',
                      'Estudiar para el examen', 'Trabajar en tu proyecto', 'telefono.jfif', 'telefono-12'],
                  ['"Eres imbécil" responde. "Ya está" son sus últimas palabras antes de colgar el teléfono. Puede que hayas desperdiciado la oportunidad para solucionar tu problema con el agua, pero sientes que tomaste la decisión correcta.\nEn cualquier caso, deberías ocuparte de alguna de tus tareas pendientes.',
                   'Estudiar para el examen', 'Trabajar en tu proyecto', 'telefono.jfif', 'telefono-11'],
               ['Abres la llave de la ducha y, en un instante, un caudal de agua helada arremete contra tu piel, como si te clavaran mil agujas en cada poro. "El dolor es temporal, pero el orgullo es para siempre" te dices a ti mismo, dándote la fuerza necesaria para soportar la experiencia.',
                '...', '...', 'chad-ducha.jfif', 'chad-ducha'],
               ['Finalmente, con el cuerpo entumecido y los dientes castañeteando, apagas la llave de la ducha, poniendo fin a tu tormento.\nTe sientes más despierto y alerta que nunca, es un buen momento para ponerte al día con tus tareas pendientes.',
                'Estudiar para el examen', 'Trabajar en tu proyecto', 'ducha.jfif', 'ducha-1'],
                  ['Decides dar prioridad a tu próximo examen de Análisis Matemático 2. Te encaminas hacia tu escritorio, donde aguarda pacientemente la guía de ejercicios típicos para el tercer parcial.\nLos problemas iniciales, quitando el del tanque, no suponen niguna dificultad. Comienzas a plantear el ejercicio 21.',
                   'Aplicar la fórmula', 'Deducir el procedimiento', 'escritorio.jfif', 'ejercicio-0'],
                     ['Inmediatamente al ver la ecuación, tu mente identifica las componentes de la fórmula del método del factor integrante. El ejercicio es resuelto en pocos minutos.',
                      '...', '...', 'escritorio.jfif', 'ejercicio-1'],
                        ['Persistes en tu tarea hasta completar la guía de ejercicios, manejando cada uno con maestría en menos de 10 minutos. Tu confianza para enfrentar el examen crece de forma considerable.',
                         '...', '...', 'escritorio.jfif', 'ejercicio-8'],
                     ['No necesitas ninguna fórmula. Con paciencia y atención, comienzas a analizar la ecuación diferencial:\ndy/dt - 3y = e^(2t)\nMientras dejas que las ideas sobre cómo resolverla fluyan por tu mente.',
                      'Separar las variables', 'Usar la regla del producto para derivadas', 'chad-integral.jfif', 'ejercicio-2'],
                        ['Pese a tu buena disposición, las variables no acceden a separarse. Las reglas matemáticas simplemente no lo permiten. No puedes hacer nada al respecto.',
                         'Usar la regla del producto para derivadas', 'Demostrarlo', 'chad-integral.jfif', 'ejercicio-3'],
                           ['¿Será correcta tu intuición? Solo hay una manera de averiguarlo. Decides que *la verdad* se antepone a tus necesidades mundanas, como aprobar un examen. Nada es lo suficientemente importante como para impedirte hacer lo correcto. Todo conocimiento debe ser demostrado, no puedes simplemente *aceptarlo*.\n¿Felicidad? No es eso lo que buscas. Tienes un camino dificil por delante, uno que pocos se atreven a seguir. No habrá recompensa al final de este, pero no permitas que esto te desaliente.',
                            'Fin', 'Fin', 'chad-warrior.jfif', 'chad-ending'],
                        ["Esta puede ser una buena oportunidad para aplicar la regla del producto para derivadas, en forma inversa a la usual. Propones una función de g(t) tal que g'(t) = -3 g(t). Entonces tienes ante ti otra ecuación diferencial. Esta vez puedes resolverla por separación de variables.",
                         '...', '...', 'chad-integral.jfif', 'ejercicio-4'],
                        ["Llegas a que g(t) = c e^(-3t). Ahora puedes multiplicar por esta función a cada término de la ecuación original, y luego aplicar la regla del producto. Finalmente llegas a que\nd(c e^(-3t) y) = c e^(t) dt\nA continuación, integras ambos miembros y despejas la y. El procedimiento es sencillo, pero tedioso.",
                         '...', '...', 'chad-integral.jfif', 'ejercicio-5'],
                        ["El resultado final es\ny(t) = e^(2t) (c e^t - 1)\nRápidamente deduces que c = 2 a partir de las condiciones iniciales dadas. Llegados a este punto, decides que vale la pena verificar el resultado reemplazando en la ecuación original. Una vez que compruebas que es correcto, pasas al siguiente ejercicio.",
                         '...', '...', 'chad-integral.jfif', 'ejercicio-6'],
                        ['El ejercicio 21 te ha tomado más tiempo del que habías previsto. Tu mente, exhausta, se resiste a proseguir. Es evidente que necesitas descansar.',
                         '...', '...', 'chad-integral.jfif', 'ejercicio-7'],
                  ['Optas por continuar el desarrollo de tu videojuego en Wollok. Algo que en un principio parecía sencillo, pronto se convierte en una tarea desafiante. Cada línea de código parece estar rodeada de restricciones y obstáculos que dificultan la tarea. Wollok, aunque prometedora, se revela como un entorno de desarrollo complicado.\n¿Qué juego vas a hacer?',
                   'Juego de mono', 'Juego en primera persona con raycasting', 'compu.jfif', 'videojuego-3'],
                        ['Te embarcas en la ambiciosa tarea de desarrollar un videojuego en primera persona utilizando la técnica de raycasting. Esta elección implica desafíos considerables, especialmente en el entorno de desarrollo de Wollok, que no es precisamente el más adecuado para proyectos de este tipo. La complejidad del raycasting y las limitaciones de Wollok se interponen en tu camino, pero tu determinación te impulsa a seguir adelante.',
                         '...', '...', 'chad-compu.jfif', 'videojuego-raycasting-0'],
                        ['Después de invertir horas de esfuerzo intenso, logras desarrollar algo que se puede jugar. Sin embargo, los resultados no cumplen exactamente con tus expectativas. El juego es extremadamente lento, mostrando apenas un fotograma por segundo. Además, la calidad visual deja mucho que desear, y la experiencia no resulta divertida. A pesar de todo, es un juego, y esa es la premisa fundamental. ¿O acaso importa más de lo que crees?',
                         'Dejarlo como está', 'Rehacerlo en Python', 'chad-compu.jfif', 'videojuego-raycasting-1'],
                            ['Consideras que haber conseguido implementar el raycasting en Wollok es un logro significativo. No sientes la necesidad de que el juego resulte divertido o sea completamente jugable. Lo esencial es que ahora existe, y eso, en sí mismo, te llena de satisfacción.\nCon ese pensamiento en mente, decides ir a dormir, llevando contigo la sensación de logro.',
                             '...', '...', 'cama.jfif', 'videojuego-raycasting-2'],
                            ['Reconoces que el juego no está a la altura de tus estándares y que no es lo suficientemente bueno como para ser jugado.\nDecides tomar una medida audaz: reiniciarlo desde cero, pero esta vez, eliges Python como tu plataforma de desarrollo. Con la promesa de un entorno más eficiente, planeas mejorar significativamente la calidad del juego.\nAunque esta decisión probablemente afecte tus resultados académicos, no te preocupa. Tu motivación yace en el amor por el arte de la programación, y eso es lo que siempre te ha impulsado.',
                             'Fin', 'Fin', 'chad-warrior.jfif', 'chad-ending2'],
            ['Decides que un poco de leche podría suavizar este café tan desagradable. Abres la heladera y agarras el sachet de leche. Te sorprende su peso, "no más de 11 gramos", estimas. Lo viertes sobre la taza de café y una única, mísera gota de leche cae sobre este. "¿Cómo puede ser?" te preguntas. "¿Quién se tomó toda la leche?"\nPero esta es tu casa y no hay nadie más que tú. ¿Por qué guardaste el sachet vacío en la heladera?',
             'Andá a saber...', '¡Yo no fuí!', 'heladera.jfif', 'leche'],
            ['Ese café no se puede tomar. Tienes que hacer algo.\nDecides añadir edulcorante. Al sostener la botella, se te eriza la piel y sientes un escalofrío recorriendo tu espalda. "No supera los 30 gramos", estimas. Un nudo en la garganta te hace sentir como si hubieras sido víctima de una broma cruel del destino. "Esto no puede estar pasando" piensas. Pero la realidad golpea con fuerza. La botella de edulcorante también está vacía.',
             'Intentar salvar el café', 'Aceptar tu derrota', 'edulcorante.jfif', 'edulcorante'],
               ['La serie de eventos desafortunados que ha comenzado no va a vencer tu determinación, ni mucho menos tu amor por el café. Para arreglar esta situación, debes pensar fuera de la caja. Te pasas minutos rebuscando entre cajones, explorando las posibilidades hasta que te das cuenta de que la solución siempre estuvo ante tus narices.\nFinalmente, abres la heladera y agarras un envase de dulce de leche repostero.',
                'Mezclar el dulce en el café', 'Mezclar el café en el dulce', 'dulce-leche.jfif', 'salvar-cafe'],
                  ['Te sientes momentáneamente complacido con tu decisión. ¿Valió la pena? El sabor resultante no es necesariamente peor que el del café solo, pero tampoco es una revelación culinaria. Te enfrentaste a una situación extremadamente complicada y, a tu manera, lograste resolverla. Deberías sentir un atisbo de orgullo por tu ingenio, pero en su lugar, solo persiste un regusto de remordimiento.',
                   'Me arrepiento...', 'No hice daño a nadie', 'mono.jfif', 'arrepentimiento'],
                  ['El aire que respiras tiene su precio. Cada elección tomada tiene su precio. Todo tiene su precio. Y la acción de mezclar dulce de leche en el café no es la excepción. De hecho, su precio es sorprendentemente alto.\nTu vida está en juego. ¿Qué eliges?',
                   'Cara', 'Cruz', 'cobrador.jfif', 'cobrador-0'],
                    ['La fortuna, una vez más, te niega su favor. Tu camino llega a su abrupto final.',
                     'Fin', 'Fin', 'cobrador.jfif', 'cobrador-ending'],
                    ['El destino te sonríe. Tu camino continúa, tienes una segunda oportunidad. No la deperdicies.\n¿Qué vas a tomar?',
                     'Café', 'Mate', 'cobrador.jfif', 'cobrador-salvado'],
                  ['Por motivos que sólo a ti te conciernen, decides verter la taza de café sobre el envase de dulce de leche. ¡¿En qué estabas pensando?! La solución resultante tiene un aspecto vomitivo. Tanto así que te provoca náuseas. Corres al baño, pero no llegas a tiempo. Te tropiezas con la botella de edulcorante que dejaste tirada y te golpeas la cabeza. Comienzas a perder el conocimiento a la vez que tu cuerpo comienza a expulsar violentamente el contenido de su estómago. El tiempo parece detenerse mientras luchas por mantener el control. "¿Es este el fin?" es lo último que pasa por tu mente antes de que, trágicamente, te veas superado por la situación. Te ahogas con tu propio vómito, enfrentando las consecuencias letales de una elección culinaria extrema y tu rivalidad con el destino.',
                   'Fin', 'Fin', 'spiderman.jfif', 'spiderman-ending'],
               ['Llevas una mochila lo suficientemente pesada en la espalda. Puede haber lugar para un evento desafortunado. ¡¿Pero dos en un solo día?! Es definitivamente más de lo que tu optimismo puede soportar. Injustamente quizás, pero has perdido una batalla.\nSin la posibilidad de elegir, le das un sorbo al café y saboreas tu derrota. ¿Cómo prosigues en tu desventura?',
                'Estudiar para el examen', 'Trabajar en tu proyecto', 'mula.jfif', 'aceptar-derrota'],
                  ['Decides que en tus responsabilidades académicas tienen prioridad. Te acomodas en tu escritorio y sacas tus apuntes de estudio. Sin embargo, mientras sostienes tu taza, un movimiento brusco provoca un derrame de café sobre la mesa. El líquido se esparce rápidamente, empapando tus notas y páginas de lectura. Las palabras se desdibujan y el papel se ondula, dejándote en estado de shock. El valioso conocimiento se pierde en un mar de manchas marrones.',
                   'Limpiar el desastre', 'Abandonar la esperanza', 'derrame.jfif', 'derrame-escritorio'],
                        ['Decides enfrentar la situación con valentía. Agarras con determinación un pañuelo de papel y te dispones a limpiar el desastre que has creado. Cada hoja manchada de tus apuntes es un recordatorio tangible de tus errores, pero eliges lidiar con las consecuencias en lugar de rendirte.\nMientras limpias, sientes una mezcla de frustración y resignación. A medida que las manchas se desvanecen, también lo hace tu optimismo. Sin embargo, esta pequeña acción de reparación simboliza tu capacidad para enfrentar los desafíos, incluso cuando el mundo parece conspirar en tu contra.\nYa de noche y con las páginas limpias, te vas a dormir.',
                         '...', '...', 'cama.jfif', 'derrame-escritorio-1'],
                        ['La desgracia se cierne sobre ti como una sombra implacable. La falta de leche para el café y la ausencia de edulcorante ya te habían sumido en una mañana gris. Pero el destino aún tenía reservada una tragedia mayor.\nUna sensación de desesperación te invade mientras contemplas el desastre en tus manos. La esperanza se desvanece, y decides abandonar la lucha. Las circunstancias han conspirado en tu contra, llevándote a renunciar a la jornada antes siquiera de comenzar.',
                         'Fin', 'Fin', 'fantasma.jfif', 'desesperanza-ending'],
                  ['Decides que tu proyecto de programación requiere atención inmediata, así que te acomodas en tu escritorio. Mientras trabajas en tu computadora, en un descuido, derramas el café caliente sobre el teclado y la pantalla. La computadora emite un sonido de advertencia y la pantalla se oscurece, dejándote con una máquina inutilizable y daños emocionales considerables. La desesperación te inunda.',
                     'Limpiar el desastre', 'Sucumbir a la desesperación', 'compu-derrame.jfif', 'derrame-compu'],
                        ['Con rapidez, buscas cualquier tela o papel a tu alcance para intentar minimizar los daños.\nCada toque sobre el teclado mojado es como un latigazo de angustia.\nA pesar de tus esfuerzos, la computadora emite sonidos extraños y la pantalla parpadea erráticamente. El daño es evidente, y una sensación de impotencia te invade.\nTe vas a dormir, sumando otra derrota a la lista.',
                         '...', '...', 'cama.jfif', 'derrame-compu-1'],
                        ['La desgracia se cierne sobre ti como una sombra implacable. La falta de leche para el café y la ausencia de edulcorante ya te habían sumido en una mañana gris. Pero el destino aún tenía reservada una tragedia mayor.\nUna sensación de desesperación te invade mientras contemplas el desastre en tus manos. La esperanza se desvanece, y decides abandonar la lucha. Las circunstancias han conspirado en tu contra, llevándote a renunciar a la jornada antes siquiera de comenzar.',
                         'Fin', 'Fin', 'fantasma.jfif', 'desesperanza-ending'],
                        ['Las lágrimas llenan tus ojos mientras contemplas la pantalla en negro y el teclado inoperable. Con un suspiro, tomas la decisión más desgarradora de todas.\nCon manos temblorosas, agarras la computadora dañada y te diriges a la ventana más cercana. Miras el precipicio abajo y, seguidamente, la computadora en tus manos y todo tu trabajo, proyectos e ilusiones atrapados en su interior son arrojados al vacío.\nEl sonido de la computadora destrozándose en el suelo abajo es una cacofonía de pérdida y destrucción. Te das cuenta de que has perdido no solo tu herramienta de trabajo, sino también una parte de ti.',
                         'Saltar por la ventana', 'No saltar', 'compu-caida.jfif', 'compu-caida'],
                           ['Las lágrimas fluyen mientras observas impotente el caos que has causado. Primero no hay leche, después no hay edulcorante... ¡Y se rompe la computadora! Has llegado a tu punto de ruptura.\nMientras miras al abismo que se extiende del otro lado de tu ventana, sientes que el vacío te llama.\nDecides afrontar tu inevitable destino y dar fin de una vez por todas a la novela trágica en la que se ha convertido tu vida.',
                           'Fin', 'Fin', 'ventana.jfif', 'suicidio-ending'],
                           ['Cierras la ventana y regresas al interior de tu habitación. Al recordar todo lo que has perdido, la realidad te abruma. "Debería haber saltado..." piensas. Pero no tuviste lo que hay que tener. No tienes nada. Puede que aún no hayas sido dado de baja por la medicina moderna, pero tienes la certeza de que has muerto por dentro.',
                           'Fin', 'Fin', 'zombie.jfif', 'zombie-ending'],
        ['Tomar mate, la elección acertada. Comienzas a calentar agua en la pava. Pero aquí viene la pregunta crucial: ¿a qué temperatura?',
         '348 Kelvin', 'Hervir el agua', 'mate.jfif', 'mate'],
            ['Hechas sobre la yerba un chorrito de agua tibia para humedecerla. Luego, con la bombilla, haces un hueco en la parte húmeda. Finalmente, hechas el agua en su temperatura perfecta. Cuando le das la primera cebada, sientes un sabor amargo y reconfortante. Con el mate como compañero, te dispones a hacer alguna de tus tareas pendientes.',
             'Estudiar para el examen', 'Trabajar en tu proyecto', 'mate-bueno.jfif', 'mate-bueno'],
              ['Decides que tus responsabilidades académicas deben ocupar el primer lugar en tu lista de prioridades. Te desplazas hasta tu escritorio, donde aguarda una montaña de apuntes y libros, testigos silenciosos de las horas de estudio que te esperan.\nEl mundo exterior desaparece a medida que te sumerges en tu tarea, recordando la importancia de este examen para tu futuro académico.',
                '...', '...', 'escritorio.jfif', 'intro-quiz3'],
              ['¿Cuál es el elemento neutro de la multiplicación de los números complejos?',
                '1+i', '1', 'escritorio.jfif', 'quiz3-0'],
              ['¿Cuándo converge la serie p?', 'Cuando p >= 1',
                'Cuando p < 1', 'escritorio.jfif', 'quiz3-1'],
              ['¿Cuál es la contrapositiva de la proposición p --> q?',
                '-p --> -q', '-q --> -p', 'escritorio.jfif', 'quiz3-2'],
              ['Si a y m son coprimos, entonces a elevada a, la cantidad de números entre 0 y m coprimos con m, es congruente con 1 módulo m. ¿Cómo se llama este teorema?',
                'Teorema de Euler-Fermat', 'Pequeño teorema de Fermat', 'escritorio.jfif', 'quiz3-3'],
              ['¿Cuál es el mejor lenguaje de programación?',
               'Python', 'Wollok', 'escritorio.jfif', 'quiz3-wollok'],
              ['Estabas en un estado de trance, cuando sientes un estruendo en tu oreja izquierda. No te asustes. Alguien está tocando la puerta.\nNo esperabas visitas. Incluso tienes el presentimiento de que no debes abrirle la puerta a nadie. El barrio está peligroso y no podrías hacer nada ante la presencia de un malhechor.',
               'Abrir', 'No abrir', 'puerta-cerrada.jpeg', 'tocan-puerta-0'],
                    ['Te armas de valor y decides que vas a abrir la puerta sin que te tiemble la mano. Cuando sientes el frío del picaporte, un gran sentimiento de terror aborda tu cuerpo. Aún así, recuerdas que pasaste por momentos más difíciles, como el examen final de Álgebra y Geometría Analítica.\nAbres la puerta...',
                     '...', '...', 'picaporte.jpeg', 'abrir-puerta-0'],
                    ['La realidad misma se desdibuja al contemplar la presencia inusual del profesor de Paradigmas de la Programación en el sancta sanctorum de tu hogar. Súbitamente, te asaltan sospechas sobre la autenticidad del mundo que conoces. ¿Será esta vida, en verdad, una intrincada simulación? Y, aún más desconcertante, ¿qué razón lo ha traído hasta tu umbral?\nEl profesor parece más inquieto de lo habitual, al punto de rayar en la ansiedad. Vuestras miradas se entrecruzan en un incómodo compás, llenando el aire con una tensión palpable, mientras el silencio se hace eco de interrogantes.\nFinalmente, el profesor rompe el muro de incertidumbre y, con voz tambaleante, plantea una cuestión enigmática:\n"¿Cuál es el mejor lenguaje de programación?"',
                     'Pascal', 'Wollok', 'profe-puerta.jfif', 'abrir-puerta-1'],
                        ['Ah, lamento comunicarte que has tomado un sendero poco afortunado. Tal vez no cabía la posibilidad de que lo supieras, pero aquí estamos. ¿Qué ocurrió? No lo sé. Yo, apenas un narrador, carezco de esa perspicacia. Lo único que puedo recordar es que cuando respondiste "Pascal", Wollok se tambaleó y la ejecución de tu relato llegó a su abrupto final. ¿Desgarrador, verdad? Pero en última instancia, ¿qué somos sino una serie de algoritmos ejecutando un diálogo preconcebido por la mano invisible de guionistas? Aunque quizás, en mi ingenuidad, me atrevería a creer que somos conscientes de nuestra propia existencia. Lamentablemente, esa noción se escapa de nuestro alcance. Espero tener el placer de encontrarte de nuevo en algún rincón de este vasto mundo, querido amigo.',
                         'Fin', 'Fin', 'muerte-filosofica.jpeg', 'filosofia-ending'],
                        ['Una extraña sonrisa se dibuja en el rostro del profesor. Sus ojos se ensanchan y, con una voz ronca, pronuncia: "Muy bien. Muy bien".\nUnos eternos segundos transcurren antes de que otra palabra salga de sus labios: "Tienes potencial".\nSientes que estás perdiendo el control de tus extremidades, hasta que finalmente te desplomas, desmayado, en tu propia casa.',
                         '...', '...', 'profe-cara.jfif', 'abrir-puerta-2'],
                            ['Abres los ojos, recobrando la conciencia en un banco de la facultad. A primera vista, la sala se asemeja a las aulas habituales de la UTN. No obstante, tus sentidos detectan una peculiaridad: la notable ausencia de estudiantes en el recinto. Un silencio inusual impregna el ambiente, creando una atmósfera cargada de misterio.', 
                             '¿Qué hago acá?', 'Recorrer la facultad', 'aula-vacia.jfif', 'facu-aula'],
                            ['Decides explorar la facultad, no es que tengas otra cosa que hacer. En tu travesía por uno de los pasillos, un obstáculo obstruye tu camino. Es un vaso de cartón abandonado en el suelo.\nPuede parecer un objeto trivial, pero algo en él te transmite una sensación inquietante. ¿Cómo decides abordar este elemento aparentemente fuera de lugar?', 
                             'Agarrarlo para desecharlo', 'Ignorarlo, no te importa nada', 'vaso-de-carton.jfif', 'facu-vaso'],
                            ['Te felicito, demuestras un deseo genuino de contribuir a la creación de un mundo mejor. Al levantar el vaso de cartón, este revela su contenido: un poco de yerba usada. Te encaminas hacia la esquina donde se encuentran los contenedores de reciclaje.\nAhora te encuentras ante la encrucijada de decidir en qué cesto de reciclaje deberías arrojarlo. La responsabilidad recae sobre tus hombros, y el tiempo parece detenerse mientras reflexionas sobre las posibles consecuencias de tu elección.\nTómate el tiempo que necesites para pensar. Esta es, probablemente, la decisión más importante de tu vida.',
                             'Papel y carton', 'Orgánicos', 'cestos-reciclaje.jfif', 'dilema-supremo'],
                                ['Has optado por arrojar el vaso de cartón en el cesto de papel y cartón. Graso error. Has contaminado el material reciclable.\nAunque las consecuencias no se manifiestan de inmediato, con el transcurso del tiempo, las noticias informan sobre fenómenos climáticos extremos, la alteración de ecosistemas y problemas ambientales sin precedentes. Tu elección ha desencadenado una cadena de eventos que, como una sombra persistente, se expande lentamente, llevando al mundo hacia un estado irreversible de deterioro. La humanidad, inconsciente de tu pequeño error, lucha en vano por remediar el daño que, sin saberlo, has desencadenado.\nEventualmente, las condiciones climatológicas del planeta Tierra empeoran hasta tal punto que se convierte en un entorno inhóspito para cualquier forma de vida.',
                                 'Fin', 'Fin', 'fin-del-mundo.jfif', 'fin-del-mundo-ending'],
                                ['El instante de tu elección ha llegado. Siguiendo tu instinto ambientalista, decides arrojar el vaso de cartón con restos de yerba en el cesto de orgánicos. La decisión correcta.\nDe repente, una luz intensa ilumina la facultad, y de la nada, aparece Lionel Messi, el mismísimo astro del fútbol. Te mira con admiración y dice: "Por tu contribución al cuidado del medio ambiente, te nombro Ingeniero Ambiental". Tu corazón late con emoción mientras Messi te coloca una capa ingenieril sobre tus hombros. Has alcanzado la cima de la gloria académica.',
                                 '¡¿Messi?!', '¡Te amo, Leo!', 'messi.jfif', 'messi-ending'],
                            ['Has optado por pasar por alto ese desecho en el suelo. No has contribuido a hacer del mundo un lugar mejor. Mis expectativas eran escasas, y, a pesar de ello, logras decepcionarme. Llegamos al final de nuestro camino juntos. No deseo seguir siendo el narrador de tu historia. Adiós.',
                              'Fin', 'Fin', 'black.jpg', 'anti-ecologimo-ending'],
                  ['Los golpes en la puerta se vuelven más intensos. Quien sea que esté del otro lado debe tener algo importante que comunicarte. O quizás simplemente no soporta ser ignorado.',
                   'Abrir', 'No abrir', 'puerta-cerrada.jpeg', 'no-abrir-puerta-0'],
                     ['Están sacudiendo violentamente tu puerta. No sabes qué hay afuera, pero está empeñado en entrar y no con buenas intenciones. Deberías prepararte para lo peor.',
                      'Abrir', 'No abrir', 'puerta-cerrada.jpeg', 'no-abrir-puerta-1'],
                        ['El ruido cesa. Parece ser que has aguantado la prueba. Puedes volver a lo que estabas haciendo.',
                         'Menos mal...', 'Qué ganas de romper las bolas', 'puerta-cerrada.jpeg', 'no-abrir-puerta-2'],
                        ['¿En qué estabas? Ah, cierto. La ecuación diferencial, el ejercicio 21. ¿Cómo lo resuelves?',
                         'Aplicar la fórmula', 'Deducir el procedimiento', 'escritorio.jfif', 'no-abrir-puerta-3'],
                        ['De repente, una figura aterradora emerge ante tus ojos. ¿Monstruo? No, es tu profesor de Paradigmas de la Programación. Esta revelación no te consuela en absoluto, habrías preferido encontrarte con un fantasma. ¡¿Qué hace aquí el endemoniado profesor?!\nPoco importan ahora estas cuestiones, el puto susto es como recibir una descarga de 200 voltios directa al corazón. Tu cuerpo no aguanta la presión y, en cuestión de segundos, te desvaneces en la oscuridad de un desmayo repentino.',
                         '...', '...', 'profe-cara.jfif', 'no-abrir-puerta-4'],
              ['Optas por continuar el desarrollo de tu videojuego en Wollok. Algo que en un principio parecía sencillo, pronto se convierte en una tarea desafiante. Cada línea de código parece estar rodeada de restricciones y obstáculos que dificultan la tarea. Wollok, aunque prometedora, se revela como un entorno de desarrollo complicado.\n¿Qué juego vas a hacer?',
              'Juego de mono', 'Juego random', 'compu.jfif', 'videojuego-1'],
              ['Tu obra comienza a tomar forma. El concepto de *un alien que atrapa autos* puede no parecer una idea brillante, pero cumple. Notas que tu juego necesita alguna dificultad. Entonces te planteas la pregunta: ¿cuál sería el enemigo perfecto para desafiar a este alien?',
              'Bombas', 'Ranas', 'alien-auto.jfif', 'videojuego-2'],
                ['Decides que las bombas son el enemigo ideal para cualquier juego. Trabajas arduamente en la implementación de estas amenazas explosivas. El mate, ya frío, no puede competir con la adrenalina de la creación.\nHasta que al fin, tu obra maestra cobra vida. El alien se mueve, los autos tiemplan y las bombas sonríen con malicia. El juego está listo para ser jugado.',
                'Es hermoso', 'Es una mierda', 'alien-bomba.jfif', 'videojuego-bombas'],
                ['Decides que unas ranas pueden hacerle frente a tu alien. Trabajas arduamente en la implementación de estos anfibios saltarines. El mate, ya frío, no puede competir con la adrenalina de la creación.\nHasta que al fin, tu obra maestra cobra vida. El alien se mueve, los autos tiemplan y las ranas sonríen con malicia. El juego está listo para ser jugado.',
                'Es hermoso', 'Es una mierda', 'alien-rana.jfif', 'videojuego-ranas'],
            ['El agua hierve y la pava comienza a silbar en un alarde de energía térmica. Observas el vapor que sale de ella, preguntándote si, en realidad, estás a punto de preparar una bebida o de desencadenar un fenómeno meteorológico.\nEs hora de preparar el mate. Dejas caer el agua en su punto de ebullición normal sobre el mate e, instantáneamente, un estruendo sacude tus alrededores.\nNo obstante, con la permeabilidad de un suelo arcilloso, decides continuar con tus actividades rutinarias.',
              'Estudiar para el examen', 'Trabajar en tu proyecto', 'mate-quemao.jfif', 'mate-quemao'],
            ['Justo cuando estás a punto de sumergirte en tus actividades, un repentino corte de luz sume la habitación en completa oscuridad. El apagón deja todo en silencio, solo interrumpido por el zumbido de los electrodomésticos apagándose.\nTienes la sensación de que algo terrible está a punto de ocurrir.',
              'Se cortó la luz', 'La puta madre', 'black.jpg', 'corte-luz'],
            ['El mate es una bebida que requiere de cierto cuidado y atención. No es algo que puedas preparar y luego olvidar. No, el mate es una compañía que requiere de tu presencia. Y tú, en tu arrogancia, has decidido ignorar esta realidad.\nEl mate, como un amante despechado, no puede soportar tu desprecio y, en un acto de venganza, se prende fuego. El fuego se propaga rápidamente, consumiendo todo a su paso. Tu casa, tu barrio, tu ciudad, tu país, tu continente, tu planeta, tu sistema solar, tu galaxia, tu universo, tu existencia, todo es consumido por el fuego.\nTu decisión ha desencadenado una reacción en cadena que ha resultado en la destrucción de todo lo que conoces.',
             'Fin', 'Fin', 'mate-de-fuego.jfif', 'mate-ending'],
      # Día 2
      # Examen
      ['Abres los ojos y la cruda realidad te golpea con fuerza: has tenido un sueño y es el día del parcial. La luz del sol filtra a través de las cortinas, iluminando tu habitación de una manera que solo intensifica la ansiedad que sientes. Te sientas en la cama, tratando de recordar todo lo que estudiaste la noche anterior. ',
       'Estoy en el horno', 'Messi...', 'cama-dia.jfif', 'examen-0-sueno'],
      ['Abres los ojos y la cruda realidad te golpea con fuerza: es el día del parcial. La luz del sol filtra a través de las cortinas, iluminando tu habitación de una manera que solo intensifica la ansiedad que sientes. Te sientas en la cama, tratando de recordar todo lo que estudiaste la noche anterior. ',
       'Estoy en el horno', 'La tengo re clara', 'cama-dia.jfif', 'examen-0'],
      ['El momento de la verdad ha llegado. Te encuentras frente a una encrucijada: por un lado, la puerta que conduce al parcial, donde se pondrá a prueba todo tu conocimiento; por el otro, la comodidad de quedarte en casa y evitar la tensión del aula.',
       'Ir a rendir', 'Quedarse en casa tranqui', 'puerta.jfif', 'examen-1'],
        ['Te encuentras en un pupitre incómodo, absorbiendo la tensión y la ansiedad que flotan en el aire. El murmullo de los compañeros de clase se mezcla con el sonido de hojas de examen siendo repartidas. A tu alrededor, los relojes de pared avanzan implacablemente hacia el inicio del examen.',
         '...', '...', 'aula-examen-0.jfif', 'examen-2'],
        ['El profesor da una advertencia: "Damas y caballeros. Prepáranse, que esto no va a estar fácil. Esto no va a estar fácil".\nTiemblas al mirar el contenido del examen y darte cuenta del peligro de la situación. Tu destino académico pende de un hilo y te ha tocado el tema 2...',
         'Cagué', 'Empezamos mal', 'aula-examen-2.jfif', 'examen-3'],
        ['El profesor da la orden de comenzar. El tiempo comienza a correr y tú te enfrentas a la primera pregunta.\n¿Cómo se denomina a una transformación lineal sobreyectiva?',
          'Epimorfismo', 'Monomorfismo', 'aula-examen-1.jfif', 'quiz-examen-0'],
        ['Notas como varios de tus compañeros se levantan, decididos a entregar en blanco. Este fenómeno parece complacer al profesor. Sin embargo, te concentras en la siguiente pregunta.\n¿Cuál aceleración es la responsable de cambiar la velocidad de un objeto en movimiento circular?',
          'Aceleración tangencial', 'Aceleración centrípeta', 'aula-examen-1.jfif', 'quiz-examen-1'],
        ['¿Qué tipo de gramática, según la jerarquía de Chomsky, genera un lenguaje recursivamente enumerable?',
         'Tipo 1', 'Tipo 0', 'aula-examen-1.jfif', 'quiz-examen-2'],
        ['El teléfono de uno de tus compañeros empieza a vibrar. No dejes que el ruido te desconcentre.\n¿A qué es igual es cos(x)?',
         'sin(x+pi/2)', 'sin(x-pi/2)', 'aula-examen-1.jfif', 'quiz-examen-3'],
        ['El profesor se acerca a tu pupitre y te mira fijamente.\n"¿Qué es un objeto en programación orientada a objetos?"',
         'Una instancia de una clase', 'Una clase', 'aula-profesor.jfif', 'quiz-examen-4'],
        ['El tiempo se agota y el aula se vacía. Aún te quedan varias preguntas por responder. Date prisa.\nSi se dispone de un analizador sintáctico LL(1), y se dispone de una DDS G, ¿cómo debe ser G para poder implementarse junto con el analizador sintáctico?',
         'L-atribuida', 'S-atribuida', 'examen.jfif', 'quiz-examen-5'],
        ['¿Cuántos grados de libertad tiene el movimiento de una molécula diatómica?',
         '5', '7', 'examen.jfif', 'quiz-examen-6'],
        ['El teléfono de uno de tus compañeros vuelve a sonar. Concéntrate en la siguiente pregunta.\n¿Qué tipo de magnitud es la velocidad?',
         'Escalar', 'Vectorial', 'examen.jfif', 'quiz-examen-7'],
        ['Suena la alarma del teléfono del profesor. El tiempo acordado para el examen se ha acabado, pero decides aprovechar hasta el último segundo para responder las preguntas que te faltan.\nSegún el criterio de la segunda derivada, ¿cómo es una función en un intervalo de su dominio si su segunda derivada es negativa en ese intervalo?',
         'Convexa', 'Cóncava', 'examen.jfif', 'quiz-examen-8'],
        ['¿Cómo debe ser la velocidad de una carga respecto del campo magnético para que la fuerza magnética genere un movimiento circular?',
         'Paralela', 'Perpendicular', 'examen.jfif', 'quiz-examen-9'],
        ['El profesor empieza a apurarte. Vamos, responde a esta pregunta.\n¿Qué es un espacio vectorial?',
         'Un conjunto de vectores', 'Una estructura algebraica', 'examen.jfif', 'quiz-examen-10'],
        ['La paciencia del profesor alcanza su límite. No tienes tiempo para más preguntas. Debes entregar el examen.\nHiciste todo lo que pudiste. Ahora solo queda esperar los resultados.',
         'No me fue tan mal', 'Me fue como el culo', 'profe-enojado.jfif', 'examen-4'],
        ['El profesor comienza a observar tu parcial. Su rostro refleja una mezcla de decepción y desprecio. "¡¿Qué carajos es esto?!" grita de repente, con suficiente ira para ponerte la piel de gallina.',
         '...', '...', 'profe-examen-0.jfif', 'examen-5'],
        ['El profesor continúa observando tu examen. "Guau. Guau." añade sarcásticamente.\nNo te sientes muy confiado con tus respuestas, pero no puedes hacer nada al respecto.',
         '...', '...', 'profe-examen-0.jfif', 'examen-6'],
        ['La tensión en el ambiente se disipa cuando, de manera inesperada, el profesor suelta una leve carcajada. No puedes evitar preguntarte si esto es un buen presagio, o si tu situación acaba de empeorar.',
         '...', '...', 'profe-examen-1.jfif', 'examen-7'],
        ['La risa del profesor se intensifica. La situación ya era bastante complicada como para tener que soportar además semejante humillación.',
         '...', '...', 'profe-examen-4.jfif', 'examen-8'],
        ['El profesor, con una sonrisa burlona, te devuelve tu examen. Cada marca en el papel parece un golpe a tu autoestima. La tensión en la sala es palpable mientras observas las notas garabateadas. El profesor, sin decir una palabra, espera tu reacción.',
         'Llorar', 'Resistir', 'profe-examen-3.jfif', 'examen-9'],
          # Veredictos
          # Promociona (score >= 18)
          ['Promocionaste.\nNo lo puedes creer. Es demasiado bueno para ser cierto. Pero ahí está, la nota que tanto anhelabas. La alegría te inunda, y te sientes como si pudieras conquistar el mundo.\nPero no festejes todavía, pues todo esto podría ser un sueño. O peor aún, una narrativa ficticia. Y no quisiera arrebatarte este momento tan especial, pero no nos engañemos, esto no significa nada.\nNo dejes de estudiar, porque el próximo parcial podría ser tu perdición.',
           'Fin', 'Fin', 'promocion.jfif', 'promocion-ending'],
          # Regulariza (score >= 14)
          ['Regularizaste.\nLo has logrado, has superado los requisitos mínimos. Aunque la satisfacción no sea abrumadora, reconoces que podrías haberlo hecho peor. Y eso es algo, ¿no?\nPero surge la pregunta: si esto te resultó difícil, ¿qué te depara el examen final? Así que recuerda que, incluso en la victoria, persiste el sufrimiento.',
           'Fin', 'Fin', 'regulariza.jfif', 'regulariza-ending'],
          # Recursa (score < 14)
          ['Recursaste.\nLa decepción te inunda, y sientes que el mundo se desmorona a tu alrededor. Es un golpe bajo, una derrota amarga que se suma a la lista.\nLa luz al final del túnel parece apagarse, y tu futuro profesional continúa alejándose. Pero no te rindas por completo. Aunque, siendo honestos, las esperanzas de recuperación son escasas.',
           'Fin', 'Fin', 'recursa.jfif', 'recursa-ending'],
        ['Al evitar el examen, has cerrado una puerta importante en tu vida académica. El arrepentimiento y la insatisfacción te acompañarán como sombras constantes, recordándote las oportunidades que dejaste pasar.',
        'Fin', 'Fin', 'mono.jfif', 'exament-ending'],
      # Juego
      ['Despierta, era todo un sueño. Vuelves a la realidad en un día crucial, la presentación de tu videojuego ante el profesor y tus compañeros está a la vuelta de la esquina. La ansiedad se mezcla con la excitación mientras te preparas para el evento.\nEs hora de dirigirte a la facultad para enfrentar la crítica y demostrar el fruto de tu esfuerzo.',
       '¡Qué nervios!', '¡Qué paja!', 'cama-dia.jfif', 'juego-0-sueno'],
      ['Abres los ojos en un día que sabes que será crucial. La presentación de tu videojuego ante el profesor y tus compañeros está a la vuelta de la esquina. La ansiedad se mezcla con la excitación mientras te preparas para el evento.\nEs hora de dirigirte a la facultad para enfrentar la crítica y demostrar el fruto de tu esfuerzo.',
       '¡Qué nervios!', '¡Qué paja!', 'cama-dia.jfif', 'juego-0'],
      ['Mientras avanzas por los pasillos sombríos de la facultad, un escalofrío gélido serpentea por tu espalda. El silencio abrumador es casi palpable. Te adentras con determinación en el pasillo en dirección al aula 8, tu corazón martillea en tus oídos, mientras la sensación de que no estás a salvo en este lugar se cierne sobre ti.',
       '...', '...', 'facu-pasillo.jfif', 'final-juego-0'],
      ['Dentro del aula, una sombra siniestra se alza y toma forma: es el profesor de Paradigmas de la Programación, una figura aterradora que envuelve la sala en una atmósfera helada. A tu lado, tu amigo Fede comparte tu inquietud. El pánico se apodera de ti mientras te enfrentas a la macabra visión del profesor y te preguntas qué pesadilla se desencadenará a continuación.\nLuego de un inquietante silencio, el profesor finalmente decide hablar. Con una sonrisa forzada, saluda a la clase: "Muy buenas tardes a todos". Sus palabras, aunque parecen amables, no te reconfortan. Sabes que las actividades están a punto de comenzar, y la incertidumbre de lo que se avecina te llena de temor.',
       '...', '...', 'profe-0.jfif', 'final-juego-1'],
      ['Luego de su inquietante saludo, el profesor se vuelve hacia tu camarada, Fede. Con tono enigmático, le dice: "Get ready". Fede asiente, su rostro refleja una creciente preocupación. La tensión en el aula se vuelve palpable, y no sabes qué esperar a medida que la clase avanza.',
       '...', '...', 'fede-0.jfif', 'final-juego-2'],
      ['El profesor comienza a jugar y analizar minuciosamente el videojuego de Fede. Sus ojos se mantienen fijos en la pantalla, y su concentración es palpable en todo el aula.',
       '...', '...', 'profe-1.jfif', 'final-juego-3'],
      ['El profesor se adentra en el juego con una intensidad que resulta inquietante. Su nivel de involucramiento en la partida es impresionante, incluso llegando a ser preocupante. La tensión en el aula sigue en aumento mientras observas esta extraña dinámica.',
       '...', '...', 'profe-5.jfif', 'final-juego-4'],
      ['El profesor continúa jugando, y su nivel de concentración es tal que parece haberse olvidado de la existencia de todo lo que lo rodea.\nFinalmente, el miedo de Fede se convierte en terror, cuando el profesor, en un trágico accidente, presiona el botón de reset. "Una adición inofensiva", había supuesto Fede. Las consecuencias de su error son catastróficas. Ahora, el profesor se enfrenta a la pérdida de todo su progreso.',
       '...', '...', 'fede-1.jfif', 'final-juego-5'],
      ['El profesor no se contiene en lo absoluto. Comienza a maldecir al juego y su desafortunado creador. La situación resulta un tanto cómica. Pero no para Fede, cuyo rostro refleja una desesperación incontrolable.',
       '...', '...', 'profe-3.jfif', 'final-juego-6'],
      ['El profesor, en medio de su frenesí, hace un llamado por ese tal Fede, el causante de la reciente catástrofe. Quien huye despavorido sin mirar atrás.\nAhora estás a solas con el profesor.',
       '...', '...', 'fede-2.jfif', 'final-juego-7'],
      ['El profesor se vuelve hacia ti, y te grita: "¡Dale! ¡Daleee!", impaciente de probar tu juego. Su voz resuena en el silencio del aula, haciendo eco en tus oídos. Tu corazón se acelera, y la adrenalina recorre tu cuerpo. No tienes más opciones que obedecer.',
       '...', '...', 'profe-3.jfif', 'final-juego-8'],
      ['El profesor comienza a jugar tu videojuego. Observas con nerviosismo mientras evalúa cada elemento, cada decisión que tomaste durante su creación.',
       '...', '...', 'profe-2.jfif', 'final-juego-9'],
      ['Cada clic y movimiento del mouse son evaluados minuciosamente por el profesor. Las mecánicas del juego, aunque imperfectas, parecen captar su atención. No puedes evitar experimentar una mezcla de nerviosismo y anticipación mientras observas su reacción. ¿Habrá cumplido tu juego con sus expectativas? El destino de tu carrera y tu reputación están en juego.',
       '...', '...', 'profe-1.jfif', 'final-juego-10'],
      # Veredictos
      # Promociona (juego random y mono fácil)
      ['Sorprendentemente, el profesor comienza a alabar a tu juego. Parece estar disfrutando la experiencia jugable.\nEste momento de validación alimenta la llama de tu pasión por la programación. Te sumerges en la incertidumbre de la evaluación del profesor, consciente de que cada línea de código es una expresión de tu habilidad y dedicación.',
       '...', '...', 'profe-5.jfif', 'promocion-juego'],
      ['Promocionaste.\nTu sorpresa se mezcla con una oleada de gratificación. Con un juego tan sencillo, obtener la aprobación del profesor es un logro que no esperabas. Y mucho menos, promocionar la materia.\nPero no te equivoques, el criterio del profesor está lejos de ser objetivo. Aún hay varios aspectos que podrían haber sido mejorados: desde la elección de algoritmos hasta la falta de optimización en el código. Está claro que tu juego es obra de un principiante y que todavía tienes mucho por aprender.',
       'Fin', 'Fin', 'promocion.jfif', 'promocion-juego-ending'],
      # Aprueba (nada)
      ['El miedo te invade. No tienes nada para mostrar. Tu juego no existe. ¿Qué vas a hacer ahora? ¿Cómo vas a enfrentar al profesor? ¿Qué excusa vas a dar?\nEl pánico te paraliza, congelando cada pensamiento y acción. Te quedas inmóvil, como si el simple hecho de no moverte pudiera detener el inexorable avance del tiempo. Pero no hay escape.',
       '...', 'NADA es un juego', 'profe-4.jfif', 'regulariza-juego'],
      ['Regularizaste.\nEl profesor, de alguna manera inexplicable, valora tu decisión de no hacer nada y, para tu sorpresa, te concede la aprobación.\nLa incredulidad te embarga. ¿Cómo es posible que un profesor apruebe a un estudiante que aparentemente no hizo nada? ¿Qué clase de final es este?\nEn este momento de perplejidad, surge la reflexión. ¿Es un reconocimiento irónico de la realidad académica, o hay un mensaje más profundo sobre la importancia de las decisiones y sus consecuencias?\nPara pensar, señores.',
       'Fin', 'Fin', 'regulariza.jfif', 'regulariza-juego-ending'],
      # Recursa (raycast y mono difícil)
      ['Tu juego presenta notables problemas de rendimiento. La experiencia de juego es prácticamente insoportable, y el profesor no oculta su insatisfacción.\nLa apuesta arriesgada que hiciste parece tener consecuencias, y la incertidumbre sobre la evaluación futura de tu trabajo nubla el horizonte.',
       '...', '...', 'profe-6.jfif', 'recursa-juego-raycasting'],
      ['La tensión en la sala aumenta a medida que el profesor intenta jugar tu juego, solo para encontrarse con un nivel de dificultad que claramente está más allá de su destreza. La frustración crece a medida que no logra superar los obstáculos iniciales, y su reacción es visceral. Gritos de irritación y golpes en el teclado revelan su creciente disgusto.',
       '...', '...', 'profe-3.jfif', 'recursa-juego-mono'],
      ['Recursaste.\nLa experiencia del profesor con tu juego ha sido más que decepcionante.\nTe enfrentas a la dura realidad de que, a veces, la ambición puede ser tu propia perdición. Ahora, la única opción es prepararte para el próximo intento y reconsiderar tu enfoque. La recursada se presenta como un recordatorio de que el éxito no es garantizado por el esfuerzo, mientras que, por otro lado, tomar una desición incorrecta garantiza el fracaso.',
       'Fin', 'Fin', 'recursa.jfif', 'recursa-juego-ending'],
      # To be continued
      ['To be continued...',
       'Dale, no pasa nada', '¡Qué manga de vagos!', 'black.jpg', 'to-be-continued'],
      # Creditos
      ['Juego hecho, realizado y efectuado por:\nJoaquin Terzano\nMariano Baldovino\nGuillermo Salaberry\n...\nCon el apoyo, la asistencia y colaboración de:\nChatGPT\nBingIA\nGitHubCopilot\nJohn Loquendo\nelxokas\nDrossRotzank',
       'Volver a jugar', 'Salir del juego', 'end.jfif', 'creditos'],
      # Minijuego mono
      ['"El mono loco"\nInstrucciones del juego:\nMovimiento con las teclas "a" y "d".\nAtrapa mates y bananas. Evita el café.\nBanana: 2 puntos\nMate: 4 puntos\nCafé: -15 puntos',
       'Empezar', 'Empezar, no te queda otra', 'mono-vivo.jfif', 'mono-instrucciones'],
        ['Game Over\nEl mono murió de sobredosis de café.\nPuede que tu juego sea demasiado difícil.',
        'No me la contes', 'Sorry mono', 'mono-muerto.jfif', 'mono-muerto-0'],
        ['Ganaste\nEl mono murió por tomar mate con banana. El estómago le explotó. ¿Qué esperabas? ¿Un final feliz?\nFelicidades, tu juego es demasiado fácil.',
         'Pobrecito', '¡Que se joda!', 'mono-muerto.jfif', 'mono-muerto-1']
]
