
# elemento: [descripcion, opcionA, opcionB, url_imagen]
lista = [
    ['¿En cuál de estos enfoques se prioriza la encapsulación, la herencia y el polimorfismo en el diseño del código', 'Programación orientada a objetos', 'Programación estructurada', 'quiz.jpg'],
    ['¿Cuál es el elemento neutro de la multiplicación de los números complejos?', '1+i', '1', 'quiz.jpg'],
    ['¿De cuál de estos teoremas se deduce el Teorema de Rolle?', 'Teorema de Fermat', 'Teorema de Lagrange', 'quiz.jpg'],
    ['¿Cuál de estos métodos es especialmente útil para ajustar una curva a un conjunto de datos observados?', 'Mínimos cuadrados', 'Polinomios de Taylor', 'quiz.jpg'],
    ['¿Qué teorema matemático se utiliza para facilitar el cálculo de flujo vectorial a través de una superficie cerrada?', 'Teorema de Stonks', 'Teorema de Gauss', 'quiz.jpg'],
    ['Todos los sistemas en el universo tienden al equilibrio ¿Cómo se conoce este fenómeno?', 'Ley de Murphy', 'Principio de entropía', 'quiz.jpg'],
    ['¿Qué instrumento se utiliza en un experimento para verificar la Ley de Boyle-Mariotte?', 'Manómetro', 'No sé, man. Soy de sistemas', 'quiz.jpg'],
    ['No has acertado ni una sola respuesta en el cuestionario. Te preguntas cómo puedes ser tan ignorante. Siento pena por ti. No es una situación que debas tomar a la ligera.\nDecides ir a buscar algo para tomar.', 'Café', 'Mate', 'fin_cuestionario.jfif'],
    ['¿Solo una respuesta correcta de siete? Me daría vergüenza… Claramente, tus conocimientos están lejos de ser sólidos. Esta es una llamada de atención para que te tomes en serio tu formación y te comprometas a mejorar. ¡Ponte a estudiar, maldita sea!\nDecides ir a buscar algo para tomar.', 'Café', 'Mate', 'fin_cuestionario.jfif'],
    ['Felicidades. Tienes más cultura que un recién nacido, pero no mucha más. Podría haber acertado más preguntas eligiendo al azar. En fin, no puedo decir que estoy decepcionado, ya que no esperaba nada de ti.\nDecides ir a buscar algo para tomar.', 'Café', 'Mate', 'fin_cuestionario.jfif'],
    ['¿No pudiste responder siete preguntas correctamente? Y eso que eran sencillas... No está tan mal, pero no es motivo de celebración. Ni muy listo, ni muy tonto.\nDecides ir a buscar algo para tomar.', 'Café', 'Mate', 'fin_cuestionario.jfif'],
    ['Parece que tuviste suerte esta vez, pero no te confíes. La suerte no golpea dos veces a la misma puerta.\nDecides ir a buscar algo para tomar.', 'Café', 'Mate', 'fin_cuestionario.jfif'],
    ['Café, la bebida de los dioses. O eso dicen... Lo cierto es que no te gusta el café. Por lo menos no la porquería de café instantáneo que compraste. Pero no te queda otra opción, así que preparas una taza.\nEl café se disuelve en el agua caliente, liberando un aroma a café quemado que llena la cocina. El olor, aunque familiar, no logra disipar tu desconfianza en la mezcla.', 'Tomar el café solo', 'Agregarle leche', 'cafe.jfif'],
    ['Tomar mate, la elección acertada. Comienzas a calentar agua en la pava. Pero aquí viene la pregunta crucial: ¿a qué temperatura?', '348 Kelvin', 'Hervir el agua', 'mate.jfif'],
    ['Con los huevos bien puestos, le das el primer sorbo al café y, al instante, un sabor amargo y asqueroso golpea tu paladar. "Es lo que hay", te dices a ti mismo con una mezcla de resignación y determinación. "No puedo desperdiciar el café". Tras cada sorbo, sientes cómo la amargura se adueña de tu lengua y el café castiga tu paladar.', '...', '...', 'chad-cafe-solo.jfif'],
    ['Decides que un poco de leche podría suavizar este café tan desagradable. Abres la heladera y agarras el sachet de leche. Te sorprende su peso, "no más de 11 gramos", estimas. Lo viertes sobre la taza de café y una única, mísera gota de leche cae sobre este. "¿Cómo puede ser?" te preguntas. "¿Quién se tomó toda la leche?"\nPero esta es tu casa y no hay nadie más que tú. ¿Por qué guardaste el sachet vacío en la heladera?', 'Andá a saber...', '¡Yo no fuí!', 'heladera.jfif'],
    ['Hechas sobre la yerba un chorrito de agua tibia para humedecerla. Luego, con la bombilla, haces un hueco en la parte húmeda. Finalmente, hechas el agua en su temperatura perfecta. Cuando le das la primera cebada, sientes un sabor amargo y reconfortante. Con el mate como compañero, te dispones a hacer alguna de tus tareas pendientes.', 'Estudiar para el examen', 'Trabajar en tu proyecto', 'mate-bueno.jfif'],
    ['El agua hierve y la pava comienza a silbar en un alarde de energía térmica. Es hora de preparar el mate. Mientras vuelcas el agua en su punto de ebullición normal sobre el mate, puedes escuchar como parte de esta se evapora al entrar en contacto con la yerba. ¡Felicidades, quemaste el mate!', '...', '...', 'mate-quemao.jfif'],
    ['Ese café no se puede tomar. Tienes que hacer algo.\nDecides añadir edulcorante. Al sostener la botella, se te eriza la piel y sientes un escalofrío recorriendo tu espalda. "No supera los 30 gramos", estimas. Un nudo en la garganta te hace sentir como si hubieras sido víctima de una broma cruel del destino. "Esto no puede estar pasando" piensas. Pero la realidad golpea con fuerza. La botella de edulcorante también está vacía.', '...', '...', 'edulcorante.jfif'],
    ['Okay Sherlock. Alguien entró en tu casa, se tomó tu leche y guardó el sachet vacío en la heladera. ¿Qué vas a hacer al respecto?', 'Investigar si te robaron algo', 'Buscar *señales*', 'sherlock.jfif']
]